(() => { const {nodes,edges,refs}=window.FOOD_WEB; const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const nodeMap=new Map(nodes.map(n=>[n.id,n])),workspace=document.querySelector('.workspace'),tabs=document.getElementById('viewTabs');
 const button=document.createElement('button');button.id='foodwebTab';button.textContent='食物网与循环';button.setAttribute('aria-pressed','false');tabs.prepend(button);
 const panel=document.createElement('section');panel.id='foodwebPanel';panel.hidden=true;
 panel.innerHTML=`<header class="food-intro"><span>FOOD WEB / MATTER CYCLE</span><h2>从一片叶，到树洞里的循环。</h2><p>实心节点关联表格记录，空心节点补充生态知识。箭头旁的文字说明关系；连线均为知识解释，不是本地捕食实证。</p><div class="food-paths"><button data-path="all" aria-pressed="true">完整食物网</button><button data-path="green">植食与捕食</button><button data-path="brown">碎屑与分解</button><button data-path="cycle">养分回归</button><button data-path="mutual">蜜露与蚂蚁</button></div></header><div class="food-layout"><div class="food-scroll"><svg viewBox="0 0 1000 790" role="group" aria-label="可点击的食物网与物质循环"><defs><marker id="foodArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#8b80c5"/></marker></defs><text class="food-row" x="32" y="28">01  绿色食物通道</text><text class="food-row" x="32" y="357">02  碎屑食物通道</text><g id="foodEdges"></g><g id="foodNodes"></g><text class="food-foot" x="32" y="760">物质可以循环 · 能量沿食物关系传递，并通过呼吸等过程散失</text></svg></div><aside id="foodDetail" aria-live="polite"></aside></div>`;
 workspace.after(panel);
 const svgNS='http://www.w3.org/2000/svg';function el(tag,attrs){const e=document.createElementNS(svgNS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e;}
 const source=key=>key?`<a href="${refs[key][1]}" target="_blank" rel="noopener">${refs[key][0]} ↗</a>`:'';
 const relatedRecords=n=>window.TREE_DATA.records.filter(r=>r.observations.some(o=>n.taxa.includes(o.name)));
 function showNode(n){const rows=relatedRecords(n);document.getElementById('foodDetail').innerHTML=`<small>${esc(n.role)}</small><h3>${esc(n.label)}</h3><p>${esc(n.text)}</p>${source(n.ref)}${rows.length?`<h4>${rows.length} 份相关表格档案</h4><p class="food-note">包含名称与痕迹记录；关联档案不等于观察到了这条食物关系。</p><div class="chips">${rows.map(r=>`<button class="chip" data-food-record="${r.id}">${r.id}</button>`).join('')}</div>`:'<p class="food-note">知识补充节点，不增加表格中的物种数、记录数或观察次数。</p>'}<h4>连接关系</h4>${edges.filter(e=>e.from===n.id||e.to===n.id).map(e=>`<button class="food-relation" data-food-edge="${e.id}">${esc(e.title)} →</button>`).join('')}`;highlight(new Set([n.id,...edges.filter(e=>e.from===n.id||e.to===n.id).flatMap(e=>[e.from,e.to])]),edges.filter(e=>e.from===n.id||e.to===n.id));}
 function showEdge(e){document.getElementById('foodDetail').innerHTML=`<small>关系解释</small><h3>${esc(e.title)}</h3><p>${esc(e.text)}</p>${source(e.ref)}<p class="food-note">基于生态知识的示意关系，未作为本项目现场观察写入表格。</p><button class="food-relation" data-food-node="${e.from}">${esc(nodeMap.get(e.from).label)}</button><button class="food-relation" data-food-node="${e.to}">${esc(nodeMap.get(e.to).label)}</button>`;highlight(new Set([e.from,e.to]),[e]);}
 function highlight(ids,activeEdges){panel.querySelectorAll('.food-node').forEach(e=>e.classList.toggle('dimmed',!ids.has(e.dataset.id)));const selected=new Set(activeEdges.map(e=>e.id));panel.querySelectorAll('.food-edge').forEach(e=>e.classList.toggle('dimmed',!selected.has(e.dataset.id)));}
 edges.forEach(e=>{const a=nodeMap.get(e.from),b=nodeMap.get(e.to),g=el('g',{class:'food-edge',role:'button',tabindex:0,'aria-label':e.title,'data-id':e.id});let d,mx,my;
  if(e.path==='cycle'&&e.to==='plant'){d=`M ${a.x+73} ${a.y+74} C 955 690, 955 722, 870 722 L 95 722 Q 32 722, 32 659 L 32 267 Q 32 222, ${b.x} ${b.y+37}`;mx=680;my=711;}
  else if(e.from==='dead'&&e.to==='fungi'){d=`M ${a.x+100} ${a.y} C 255 360, 520 360, ${b.x+45} ${b.y}`;mx=385;my=378;}
  else if(e.path==='mutual'){const back=e.from==='ants',lane=back?338:200;d=`M ${a.x+73} ${a.y+(back?74:0)} C ${a.x+73} ${lane}, ${b.x+73} ${lane}, ${b.x+73} ${b.y+(back?74:0)}`;mx=655;my=lane+(back?-2:-8);}
  else if(e.from==='spring'&&e.to==='pred'){d=`M ${a.x+146} ${a.y+30} C 815 640, 815 125, ${b.x+146} ${b.y+30}`;mx=792;my=380;}
  else{const ax=a.x+65,ay=a.y+30,bx=b.x+65,by=b.y+30,dx=bx-ax,dy=by-ay,len=Math.hypot(dx,dy),ux=dx/len,uy=dy/len;const sx=ax+ux*54,sy=ay+uy*42,tx=bx-ux*60,ty=by-uy*42;d=`M ${sx} ${sy} L ${tx} ${ty}`;mx=(sx+tx)/2;my=(sy+ty)/2-7;}
  g.append(el('path',{d,class:'food-edge-hit'}),el('path',{d,class:'food-edge-line','marker-end':'url(#foodArrow)'}));const t=el('text',{x:mx,y:my,'text-anchor':'middle'});t.textContent=e.label;g.append(t);g.addEventListener('click',()=>showEdge(e));g.addEventListener('keydown',ev=>{if(['Enter',' '].includes(ev.key)){ev.preventDefault();showEdge(e)}});document.getElementById('foodEdges').append(g);
 });
 nodes.forEach(n=>{const rows=relatedRecords(n),g=el('g',{class:'food-node '+(rows.length?'recorded':'concept'),transform:`translate(${n.x},${n.y})`,tabindex:0,role:'button','aria-label':n.label,'data-id':n.id});g.append(el('rect',{width:146,height:74,rx:18}));const title=el('text',{x:73,y:31,'text-anchor':'middle'});title.textContent=n.label;const role=el('text',{x:73,y:53,'text-anchor':'middle',class:'food-node-role'});role.textContent=n.role;g.append(title,role);g.addEventListener('click',()=>showNode(n));g.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();showNode(n)}});document.getElementById('foodNodes').append(g)});
 function activate(){workspace.hidden=true;panel.hidden=false;tabs.querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});document.getElementById('resetButton').hidden=true;}
 button.addEventListener('click',activate);tabs.addEventListener('click',e=>{if(e.target.closest('[data-view]')){workspace.hidden=false;panel.hidden=true;button.classList.remove('active');button.setAttribute('aria-pressed','false');document.getElementById('resetButton').hidden=false;window.dispatchEvent(new Event('resize'));}});
 panel.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.path){const subset=b.dataset.path==='all'?edges:edges.filter(x=>x.path===b.dataset.path);highlight(new Set(subset.flatMap(x=>[x.from,x.to])),subset);panel.querySelectorAll('[data-path]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}if(b.dataset.foodNode)showNode(nodeMap.get(b.dataset.foodNode));if(b.dataset.foodEdge)showEdge(edges.find(x=>x.id===b.dataset.foodEdge));if(b.dataset.foodRecord){tabs.querySelector('[data-view="all"]').click();document.dispatchEvent(new CustomEvent('foodweb:record',{detail:b.dataset.foodRecord}));}});
 showNode(nodes[0]);highlight(new Set(nodes.map(n=>n.id)),edges);activate();
})();
